Added router for setting new passwords
tauanesales/BACK-MATE85-Topicos-em-sistemas-de-informacao-e-web-i pull request #54
Opened 2024-06-15 01:42 UTC by JeanExtreme002

## Descrição

Adiciona uma rota para permitir o usuário redefinir a senha.

## Que tipo de PR é este? (marque todos os aplicáveis)

- [ ] 🍕 Recurso (Feature)
- [ ] 🐛 Correção de Erro (Bugfix)
- [ ] 📝 Atualização de Documentação
- [ ] 🎨 Estilização
- [ ] 🧑‍💻 Refatoração de Código
- [ ] 🔥 Melhorias de Desempenho
- [ ] ✅ Testes (unitários/integração/e2e)
- [ ] 🤖 Compilação
- [ ] 🔁 Integração Contínua
- [ x ] 📦 Tarefa (Nova versão)
- [ ] ⏩ Reverter

## Issues/Tickets e Documentos Relacionados

## Capturas de Tela/Gravações para Dispositivos Móveis e Desktop

## Passos para a QA

## Adicionado à Documentação?

## [opcional] Existem tarefas pós-implementação que precisamos realizar?

2024-06-15 02:26 UTC, tauanesales requested changes

2024-06-15 02:26 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +@router.post("/auth", response_model=NewPasswordCodeAuth, status_code=status.HTTP_200_OK)
```suggestion
@router.post("/auth", response_model=Union[Aluno, Professor], status_code=status.HTTP_200_OK)
```

2024-06-15 02:26 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +    return ServiceNewPassword.authenticate(db, request.email, request.token)
`NewPasswordCodeAuth` não possui o parâmetro `email`.

2024-06-15 02:28 UTC, tauanesales commented on src/api/services/new_password.py
> +        return user
Validar se faz sentido retornar o usuário, ao invés de nulo.

2024-06-15 02:28 UTC, tauanesales commented on src/api/services/new_password.py
> +        return user
Validar se faz sentido retornar o usuário, ao invés de nulo.

2024-06-15 02:29 UTC, tauanesales commented on src/api/services/new_password.py
> +        return user
Validar se faz sentido retornar o usuário, ao invés de nulo.

2024-06-15 02:38 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +def set_new_password(request: NewPasswordChange, db: Session = Depends(get_db)):
```suggestion
async def set_new_password(request: NewPasswordChange, db: Session = Depends(get_db)):
```
Acredito que todos endpoints deveriam ser assíncronos.

2024-06-15 02:39 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +def authenticate(request: NewPasswordCodeAuth, db: Session = Depends(get_db)):
```suggestion
async def authenticate(request: NewPasswordCodeAuth, db: Session = Depends(get_db)):
```
Acredito que todos endpoints deveriam ser assíncronos.

2024-06-15 02:39 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +def create_token(request: NewPasswordRequest, db: Session = Depends(get_db)):
```suggestion
async def create_token(request: NewPasswordRequest, db: Session = Depends(get_db)):
```
Acredito que todos endpoints deveriam ser assíncronos.

2024-06-15 02:40 UTC, tauanesales commented
Escrever testes para a nova funcionalidade

2024-06-15 02:45 UTC, JeanExtreme002 commented on src/api/entrypoints/new_password/views.py
> +    return ServiceNewPassword.authenticate(db, request.email, request.token)
Ele herda de NewPasswordRequest

2024-06-15 04:50 UTC, tauanesales requested changes

2024-06-15 04:50 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +    ServiceNewPassword.set_new_password(db, request.email, request.nova_senha)
Esse endpoint sempre aceita a nova senha. É possível alterar qualquer senha sem passar pelo processo de criação de token e autenticação.

2024-06-15 18:53 UTC, tauanesales requested changes

2024-06-15 18:53 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +@router.post("/create_token", response_model=NewPasswordCodeAuth, status_code=status.HTTP_201_CREATED)
O endpoint retorna o token. Dessa forma, qualquer um poderia obter acesso à conta de outra pessoa sem ter acesso ao e-mail ao olhar o retorno da requisição. Como o retorno dessa requisição não precisa ser utilizado para nada, acredito que faz mais sentido retornar nulo (None).

2024-06-15 18:57 UTC, JeanExtreme002 commented on src/api/entrypoints/new_password/views.py
> +@router.post("/create_token", response_model=NewPasswordCodeAuth, status_code=status.HTTP_201_CREATED)
O retorno da requisição é utilizado para os testes unitários. Sem ele, seria necessário fazer alguma gambiarra pra conseguir recuperar o token nos testes. E como o acesso é feito apenas através do front, não seria um risco assim.

2024-06-15 19:36 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +@router.post("/create_token", response_model=NewPasswordCodeAuth, status_code=status.HTTP_201_CREATED)
Todas as requisições são registradas na network e podem ser vistas ao apertar F12. Bastaria um usuário mal intencionado de computação para resetar a senha de um coordenador e apagar tudo que ele puder apagar, por exemplo. Isso é uma falha de segurança grave.

Utilize pytest_mock e faça o mock do retorno da função de geração de token para retornar um valor padrão. Dessa forma você saberá qual token está sendo criado.

2024-06-15 20:02 UTC, tauanesales commented on src/api/entrypoints/new_password/views.py
> +@router.post("/create_token", response_model=NewPasswordCodeAuth, status_code=status.HTTP_201_CREATED)
Segue vídeo de demonstração:
https://github.com/tauanesales/BACK-MATE85-Topicos-em-sistemas-de-informacao-e-web-i/assets/62819445/27627cc5-bcf2-43bd-860c-9731733efaf1

Por exemplo, ao resetar a senha, eu poderia inserir qualquer e-mail no front e imediatamente teria acesso ao token que foi enviado para a pessoa sem ter que acessar o e-mail dela. Inclusive, ao gravar esse vídeo, encontrei outra falha de segurança. A senha_hash é retornada para o front, e não deveria.

2024-06-15 23:55 UTC, tauanesales requested changes

2024-06-15 23:55 UTC, tauanesales commented on src/api/templates/new_password_token.html
> +</p>
O e-mail que está chegando está ficando tudo em uma linha, além de o token não ter um destaque muito grande:
![image](https://github.com/tauanesales/BACK-MATE85-Topicos-em-sistemas-de-informacao-e-web-i/assets/62819445/948a9adb-48d6-410f-a434-cad8ee189adb)

Sugestão:
```suggestion
<div style="margin: 0 10%; border: 5px rgb(174,203,250) double; padding: 15px 25px; border-radius: 20px; max-width: 700px;">
  <h1>Olá {name},</h1>
  <p>Recebemos uma solicitação para redefinição de senha. Siga as instruções abaixo para cadastrar uma nova senha:</p>
  <ol>
      <li>Copie o código abaixo;</li>
      <li>Cole o código no campo e você será direcionado para uma página onde poderá criar uma nova senha.</li>
      <li>Digite sua nova senha e confirme.</li>
      <li>Clique em "Salvar" para concluir o processo.</li>
  </ol>
  <h1 style="margin: auto; border: 3px rgb(174,203,250) double; border-radius: 15px; padding: 5px 15px; width: fit-content;">{token}</h1>
  <br>
  <p>Se você não solicitou essa alteração, ignore este e-mail ou entre em contato com nosso suporte.</p>
  <p>Atenciosamente,</p>
  <p>PGCop</p>
</div>
```

Ficaria assim:
![image](https://github.com/tauanesales/BACK-MATE85-Topicos-em-sistemas-de-informacao-e-web-i/assets/62819445/b20518bf-fb65-4a48-b480-dab59483b213)

2024-06-16 00:12 UTC, tauanesales commented on src/api/templates/task_near_to_deadline.html
Usar sugestões do template de reset de senha aqui também, para padronizar.
Obs.: as quebras de linhas no texto são ignorados no html (`Atenciosamente, PGCop` irá aparecer em apenas uma linha). Deve-se utilizar tags HTML para que as quebras de linha aconteçam.

2024-06-16 00:12 UTC, tauanesales commented on src/api/templates/task_past_to_deadline.html
Usar sugestões do template de reset de senha aqui também, para padronizar.
Obs.: as quebras de linhas no texto são ignorados no html (`Atenciosamente, PGCop` irá aparecer em apenas uma linha). Deve-se utilizar tags HTML para que as quebras de linha aconteçam.

2024-06-16 01:14 UTC, merged